s# .github/workflows/actualizar-db.yml
name: Actualizar Base de Datos

on:
  schedule:
    # Esto significa "cada 5 minutos".
    # Ejecutará en los minutos 0, 5, 10, ..., 55 de cada hora.
    # Las horas y días se basan en UTC.
    - cron: '*/5 * * * *'

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar al API Endpoint de actualización
        run: |
          # Reemplaza 'TU_URL_VERCEL' con la URL de tu despliegue en Vercel
          # Reemplaza 'TU_SECRETO_API' con el secreto que definas para proteger tu API
          curl -X GET "https://TU_URL_VERCEL/api/actualizar-db?secret=${{ secrets.API_CRON_SECRET }}"
        env:
          # Define este secreto en las configuraciones de tu repositorio de GitHub
          API_CRON_SECRET: ${{ secrets.API_CRON_SECRET }}